### ISSUE TITLE
Contributing APSR article class file

### ISSUE THREAD

**Issue by anhqle** [leeper/apsa-leeper.bst#1]
While submitting to APSR I put my preamble into a class file to be reusable.

I was going to put this class file on my own github, but to maximize sharing impact, I think we may want to pool these resources together into one central place. I found your bst very helpful, so I'd love to contribute here.

1. Do you know if similar class / style / bst file exist for Poli Sci journals?

2. Would you want to have a central repo as suggested above?

**Comment by leeper** [comment]
I don't know of a central repo. I would be happy to make this into such a repo.

**Comment by anhqle** [comment]
I set up a repo here with your bst file included. https://github.com/LaDilettante/polsci_journal_latex

Thanks for the bst file! It really helps with my Mendeley struggle.
