### ISSUE TITLE
How to install and use the .bst file

### ISSUE THREAD

**Issue by hugocmachado** [leeper/apsa-leeper.bst#2]
Hi, thank you for your work with this, it's very useful and thorough! I'm a newbie to Latex and I was wondering how I can get this to work. I've downloaded the .bst file and placed it in the same folder of the test .tex file I'm working on. My .bib file is also in the same folder. I tried this code:

    \documentclass[12pt]{article}
    \usepackage{fullpage}

    \begin{document}

     Here is something I would like to reference \cite{Popova2012}.

    \bibliography{test1}
    \bibliographystyle{apsa-leeper}
    \end{document} 

But the citation output in the pdf returns `[?]`. I'm working on Windows 10, TexWorks editor. Do you think you can help me with this, please? Thanks in advance!

**Comment by leeper** [comment]
You need to run `pdflatex` and `bibtex` per the "Compile" instructions here: http://www.bibtex.org/Using/
